/**
 * Playground Task API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { TaskDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TaskControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/tasks/{id}/complete
     * @param id 
     */
    completeTask(id: number, extraHttpRequestParams?: any): Observable<TaskDto>;

    /**
     * 
     * 
     * @endpoint get /api/tasks
     */
    getAllTasks(extraHttpRequestParams?: any): Observable<Array<TaskDto>>;

}
