/**
 * Playground Task API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskDto { 
    id?: number;
    title?: string;
    done?: boolean;
}

